### ISSUE TITLE
zcrypto can output invalid base64 for certs' subject_key_id

### ISSUE THREAD

**Issue by cdzombak** [zmap/zcrypto#115]
The following certificates have `parsed.subject_key_id` values that the Censys frontend fails at parsing as base64 and hex-encoding:

* https://censys.io/certificates/ac3dd8e76229769a32edb80f554ce8af7c87fa51e8d08610ed1f2fb9b6120596/table
* https://censys.io/certificates/2d69a9ac031d3017d49cc7d92084434163281a1f14a8cb9ce027097c6dc4978d/table
* https://censys.io/certificates/6d9fcb96023bb55bb8b0899ac54399e413dab98273080c07d56d999469bf7d1d/table
* https://censys.io/certificates/178a247823ed93e8ec517d04421e7e557c13d1a7952d51de19e8651611ccccee/table

@zakird asked me to "file a bug in ZCrypto and figure out why it's outputting invalid b64." for these certs.

**Comment by justinbastress** [comment]
It seems that the SKI (and AKI) are unconditionally (re-)hex-encoded in the JSON Marshaling -- https://github.com/zmap/zcrypto/blob/master/x509/extensions.go#L356 -- so a normal `subject_key_id` would be doubly hex-encoded in our intermediate JSON format, so it would only have octets starting with 3 or 4 (30-39, 41-46).

But, even if the original SKI in the certificate was not a hex encoded octet string, if it was something like "AUTO_GENERATED" as in one of the cases here, the output should still be valid hex.

So, that would seem to indicate that the problem is somewhere on the decoding side -- i.e. we are (usually correctly) assuming that the raw SKI value is indeed hex ASCII, so it e.g. decodes it once during the unmarshaling, and then decodes it again at the frontend (where it fails).

In that case, Chris's frontend fix is probably the right one -- though I don't think SKI is actually *invalid* if it's not the usual `hex(SHA1(DER(SPKI)))` -- see e.g. https://tools.ietf.org/html/rfc5280#section-4.2.1.2, especially the "SHOULD".

**Comment by justinbastress** [comment]
Confirmed that `x509.ParseCertificate(weirdSKICert)` returns the hex-encoded value:
```
    "subject_key_id": "4155544f5f47454e4552415445",
```
And for a cert with a normal SKI:
```
    "subject_key_id": "967f757ce883d691a36a0deb97bed28710fb769a"
```

So in both cases, the value of the raw OCTET STRING is found when hex-decoding it...so it seems that this isn't a problem with zcrypto.

FWIW, looking at some of the JSON files in ztag (e.g. https://github.com/zmap/ztag/blob/master/ztag/devices/device_with_pop3.json#L45), the data there ends up as a base64 string, not a hex string: 
```
                                "subject_key_id": "t3rhezKWKeJuka2XkeXhCBN3wzQ=", 
```

I don't have a "weird" case to try there, but grabbing that raw cert data from censys (https://censys.io/certificates/0107c3cd44758fdb7531d2498383f75fa46cb68ecbb267854463d20eeba30217/raw), I can confirm that the base64 data there is the raw base64 encoding of the OCTET STRING.

**Comment by cdzombak** [comment]
Thanks for looking into this, @justinbastress. So to be sure I follow: this ticket can be closed as "not a bug," and I need to finesse my frontend fix to more clearly indicate what's happening with these certs?
