### ISSUE TITLE
When will tls1.3 support be added to the main branch

### ISSUE THREAD

**Issue by jiaocoll** [zmap/zcrypto#378]
I think tls1.3 is a common requirement among many users and should be prioritized for updates

**Comment by dadrian** [comment]
When someone implements it. It will likely have to be external, I believe the core maintainers are busy on other projects in the ZMap organization. If I manage to get ZLint back into shape, I might take a stab at TLS 1.3 because sometimes the former grad student inside me wakes up and reminds me to hate myself.
